# Generated by Django 5.0.6 on 2024-08-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('round', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
