# Generated by Django 5.0.6 on 2024-08-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_interview_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
