# Generated by Django 5.0.6 on 2024-08-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interview_size_interview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='linkdin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
