# Generated by Django 5.0.6 on 2024-08-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_interview_comment_interview_hr_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='hr_contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interview',
            name='hr_name',
            field=models.CharField(max_length=100),
        ),
    ]
