# Generated by Django 5.0.6 on 2024-08-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_alter_interview_hr_contact_alter_interview_hr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='round',
            field=models.CharField(choices=[('Technical-1', 'Technical-1'), ('Technical-2', 'Technical-2'), ('Managerial Round', 'Managerial Round'), ('HR', 'HR'), ('Other', 'Other')], max_length=100),
        ),
    ]
