# Generated by Django 5.0.6 on 2024-08-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_hr_alter_interview_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='discription',
            new_name='description',
        ),
    ]
