# Generated by Django 5.0.6 on 2024-08-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_rename_discription_hr_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
